# Generated by Django 5.1.15 on 2026-07-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_run_state_schema_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
