# Generated by Django 5.1.15 on 2026-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_start_date_cohort_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='deployed_for_faculty_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='deployed_for_students_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
