# Generated by Django 5.1.15 on 2026-07-04 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cohort_deployed_for_faculty_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
