# Generated by Django 5.1.15 on 2026-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cohort_days_per_week_cohort_enrollment_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='round_extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
