# Generated by Django 5.1.15 on 2026-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cohort_round_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='advisor_hourly_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
