# Generated by Django 5.1.15 on 2026-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cohort_advisor_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='advisor_hourly_rate',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor')], default='STUDENT', max_length=20),
        ),
    ]
