# Generated by Django 5.1.15 on 2026-08-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cohort_advisor_hourly_rate_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='send_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
