# Generated by Django 5.1.15 on 2026-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invitation_send_error_invitation_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='current_round_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
