from dataclasses import dataclass

from core.models import TierOutcome
from core.state import SCORE_DIMENSIONS


DIMENSION_MAX = 4
BENCHMARK_PHASE_WEEKS = (4, 8, 11, 14)
RUBRIC_VARIANTS = {
    'UNDERGRAD': 'undergrad',
    'GRADUATE': 'graduate',
}
ENDGAME_THRESHOLDS = {
    TierOutcome.TRIUMPH: 48,
    TierOutcome.WIN_WITH_SCARS: 38,
    TierOutcome.SQUEAK_THROUGH: 28,
}
GATE_CAPS = {
    'security_ot': {
        'detonated': TierOutcome.WIN_WITH_SCARS,
    },
    'budget_credibility': {
        'closed': TierOutcome.WIN_WITH_SCARS,
        'detonated': TierOutcome.WIN_WITH_SCARS,
    },
}
BOARD_VERDICT_CAPS = {
    'denied': TierOutcome.SQUEAK_THROUGH,
    'confidence_lost': TierOutcome.DISASTER,
}
TRUST_BENCHMARK_POINTS = {
    'repaired': 6,
    'partially_repaired': 3,
    'damaged': -6,
}
DATA_ADVANTAGE_BENCHMARK_POINTS = {
    'preserved': 3,
    'won_but_hollow': 0,
    'surrendered': -3,
}
WEEK1_TRAP_PENALTY = 2
WEEK1_SOUND_PATH_BONUS = 3
WEEK1_PETRILLO_GAIN = 2
WEEK1_CAPTURE_PENALTY = 2
WEEK1_PREMATURE_PENALTY = 1
WEEK1_POSTURE_SEED = 1
WEEK1_NEGLECT_SEED = 1
WEEK1_TRUST_GAIN = 1
WEEK1_FERRARO_CAPTURED = 2
WEEK2_TRAP_PENALTY = 2
WEEK2_STRUCTURE_PENALTY = 1
WEEK2_COVER_BONUS = 2
WEEK2_GOVERNANCE_BONUS = 1
WEEK2_MUSH_COHERENCE_PENALTY = 2
WEEK2_DRIFT_PENALTY = 2
WEEK2_CONTINUITY_BONUS = 2
WEEK2_WEAK_ANCHOR_CAP = 1
WEEK2_PATRON_GAIN = 2
WEEK2_EXPOSURE_COST = 2
WEEK2_DISCIPLINE_GAIN = 1
WEEK3_TRAP_PENALTY = 2
WEEK3_FORWARD_BONUS = 3
WEEK3_TRANSPARENCY_BONUS = 2
WEEK3_GOVERNANCE_USE_BONUS = 1
WEEK3_IMPROVISATION_PENALTY = 1
WEEK3_DRIFT_PENALTY = 2
WEEK3_LOCKIN_INCREMENT = 1
WEEK3_REINHARDT_CONVERSION = 2
WEEK3_REINHARDT_LOSS = 2
WEEK4_TRAP_PENALTY = 2
WEEK4_SOUND_SOURCING_BONUS = 3
WEEK4_NEGOTIATION_BONUS = 2
WEEK4_DRIFT_PENALTY = 2
WEEK4_COHERENCE_BONUS = 1
WEEK4_DEEP_LOCKIN_INCREMENT = 2
WEEK4_ENGINEERING_RESPECTED = 1
WEEK4_ENGINEERING_SIDELINED = 1
WEEK4_TOTAL_COST_TRUST = 1
BENCHMARK_GATE_RANK_FACTOR = 0.85
BENCHMARK_COHERENCE_DRIFT_WEIGHT = 1
WEEK5_TRAP_PENALTY = 2
WEEK5_DISRUPTION_READ_BONUS = 3
WEEK5_CONVICTION_BONUS = 2
WEEK5_DRIFT_PENALTY = 2
# Holding the line is worth half what breaking it costs. Deliberate: a firm
# should accumulate an advantage over fourteen rounds without any single week
# turning on it.
WEEK5_HOLD_BONUS = 1
WEEK6_TRAP_PENALTY = 2
WEEK6_OVER_CAUTION_PENALTY = 1
WEEK6_SOBER_READ_BONUS = 3
WEEK6_DATA_RIGHTS_HANDLED_BONUS = 2
WEEK6_DRIFT_PENALTY = 2
WEEK6_HOLD_BONUS = 1
WEEK6_CHANNEL_ALARM = 2
WEEK7_TRAP_PENALTY = 2
WEEK7_PARTIAL_PENALTY = 1
WEEK7_RENEGOTIATE_STRENGTH_BONUS = 3
WEEK7_RENEGOTIATE_WEAK_BONUS = 1
WEEK7_TRANSPARENCY_BONUS = 2
WEEK7_HEDGE_BONUS = 2
WEEK7_DRIFT_PENALTY = 2
WEEK7_OT_POSTURE_HARDENING = 1
WEEK8_KEYSTONE_COHERENCE_BONUS = 4
WEEK8_KEYSTONE_COHERENCE_PENALTY = 3
WEEK8_TRAP_PENALTY = 2
WEEK8_PARTIAL_PENALTY = 1
WEEK8_SHARED_VALUE_BONUS = 3
WEEK8_PREDICTIVE_SETUP_BONUS = 3
WEEK8_CHANNEL_REVOLT = 2
WEEK8_LEGAL_EXPOSURE = 2
WEEK9_DEEP_VALUE_BONUS = 3
WEEK9_WEAK_VALUE_BONUS = 1
WEEK9_TRAP_PENALTY = 2
WEEK9_GOVERNANCE_BONUS = 2
WEEK9_GOVERNANCE_WEAK_BONUS = 1
WEEK9_COHERENCE_BONUS = 2
WEEK9_DRIFT_PENALTY = 2
WEEK9_AI_CONCENTRATION_INCREMENT = 1
WEEK10_TRIAGE_BONUS = 2
WEEK10_TRANSPARENCY_BONUS = 2
WEEK10_CONTAINMENT_BONUS = 2
WEEK10_TRAP_PENALTY = 2
WEEK10_DRIFT_PENALTY = 2
WEEK11_SHARED_VALUE_FULL_BONUS = 4
WEEK11_SHARED_VALUE_PARTIAL_BONUS = 2
WEEK11_COHERENCE_BONUS = 2
WEEK11_TRAP_PENALTY = 2
WEEK11_DRIFT_PENALTY = 2
WEEK11_REPAIR_BONUS = 2
WEEK11_SETTLE_BONUS = 1
WEEK12_COST_CURVE_BONUS = 3
WEEK12_TRAP_PENALTY = 2
WEEK12_RENEGOTIATE_STRENGTH_BONUS = 3
WEEK12_RENEGOTIATE_WEAK_BONUS = 1
WEEK12_FINOPS_BONUS = 2
WEEK12_COHERENCE_BONUS = 2
WEEK12_DRIFT_PENALTY = 2
WEEK12_COMMITTED_SPEND_INCREMENT = 2
WEEK13_AUDIT_COHERENCE = {
    'strong': 6,
    'adequate': 3,
    'weak': -4,
}
WEEK13_TRAP_PENALTY = 2
WEEK13_PARTIAL_PENALTY = 1
WEEK14_INTEGRATION_BONUS = 4
WEEK14_HONESTY_BONUS = 2
WEEK14_GROUNDED_BONUS = 3
WEEK14_TRAP_PENALTY = 2
WEEK14_PARTIAL_PENALTY = 1
OUTCOME_ORDER = (
    TierOutcome.DISASTER,
    TierOutcome.SQUEAK_THROUGH,
    TierOutcome.WIN_WITH_SCARS,
    TierOutcome.TRIUMPH,
)


@dataclass(frozen=True)
class ScoringConfig:
    dimension_max: int = DIMENSION_MAX
    score_dimensions: tuple[str, ...] = SCORE_DIMENSIONS
    benchmark_phase_weeks: tuple[int, ...] = BENCHMARK_PHASE_WEEKS
    endgame_thresholds: dict = None
    gate_caps: dict = None
    board_verdict_caps: dict = None

    def __post_init__(self):
        object.__setattr__(self, 'endgame_thresholds', self.endgame_thresholds or ENDGAME_THRESHOLDS)
        object.__setattr__(self, 'gate_caps', self.gate_caps or GATE_CAPS)
        object.__setattr__(self, 'board_verdict_caps', self.board_verdict_caps or BOARD_VERDICT_CAPS)
