# Generated by Django 5.1.4 on 2026-06-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('module_path', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_payload', models.JSONField(default=dict)),
                ('deliverable_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('briefing_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BRIEFING', 'Briefing'), ('CONSULTATION', 'Consultation'), ('SUBMITTED', 'Submitted'), ('SCORED', 'Scored')], default='BRIEFING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_instances', to='core.run')),
                ('score_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_week_instance', to='scoring.scorerecord')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_week_instance', to='weeks.submission')),
            ],
            options={
                'ordering': ['run_id', 'week_number'],
                'unique_together': {('run', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='week_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_payload', to='weeks.weekinstance'),
        ),
    ]
