# Generated by Django 5.1.15 on 2026-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0016_week14_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekinstance',
            name='preamble',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weekinstance',
            name='preamble_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weekinstance',
            name='preamble_problem',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
