# Generated by Django 5.1.4 on 2026-06-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_week', models.PositiveSmallIntegerField()),
                ('standings', models.JSONField(default=list)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='core.cohort')),
            ],
            options={
                'ordering': ['cohort__name', 'after_week'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_judgment', models.IntegerField(default=0)),
                ('execution_consequence', models.IntegerField(default=0)),
                ('coherence', models.IntegerField(default=0)),
                ('deliverable_quality', models.IntegerField(default=0)),
                ('auto_components', models.JSONField(default=dict)),
                ('instructor_components', models.JSONField(default=dict)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
