# Generated by Django 5.1.4 on 2026-06-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        ('weeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='week_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='weeks.weekinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='benchmark',
            unique_together={('cohort', 'after_week')},
        ),
    ]
