# Generated by Django 5.1.15 on 2026-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='applied_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
