# Generated by Django 5.1.15 on 2026-08-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0006_groupsession_groupturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorsession',
            name='advisor_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advisorsession',
            name='group_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='advisors.groupsession'),
        ),
        migrations.AlterField(
            model_name='advisorsession',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='advisors.conversation'),
        ),
    ]
