"""
Django settings for digitalco project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

# Load a project-root .env so DIGITALCO_LLM_PROVIDER, ANTHROPIC_API_KEY, and the
# rest are available without exporting them in the shell. Real environment
# variables still win over the file.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7nq43usz8+%#a%okz_(dnjr##o_k0qy@*8kv9cc@r66-!a)p)z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "erp.flexee.org",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'weeks',
    'advisors',
    'engine',
    'scoring',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digitalco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digitalco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

LOGIN_REDIRECT_URL = 'web:student_briefing'
LOGOUT_REDIRECT_URL = 'login'

# --- Deployment configuration (env-driven; added for hosted runs) ---
# Laptop behaviour is unchanged: with no env vars set, DEBUG stays on and the
# existing dev SECRET_KEY is used. For a public host, set DJANGO_DEBUG=0,
# DJANGO_SECRET_KEY, and DJANGO_ALLOWED_HOSTS. See the deployment runbook.
import os
import sys

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", SECRET_KEY)
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Section 7 un-stub: select a real advisor provider via the environment.
DIGITALCO_LLM_PROVIDER = os.environ.get("DIGITALCO_LLM_PROVIDER", "echo")

# Under `manage.py test`, never talk to a real provider. A developer .env sets a
# live key for local play; without this the suite makes paid API calls and its
# results depend on the network. Tests that exercise a generator pass their own
# client explicitly, so this only affects code that resolves one implicitly.
if "test" in sys.argv:
    DIGITALCO_LLM_PROVIDER = "echo"

# ---- email -----------------------------------------------------------------
# Defaults to "console" on purpose: a checkout without credentials prints
# invites rather than appearing to send them. Set MAIL_BACKEND=mailjet in .env
# to actually deliver.
MAIL_BACKEND = os.environ.get("MAIL_BACKEND", "console")
MAILJET_API_KEY = os.environ.get("MAILJET_API_KEY", "")
MAILJET_API_SECRET = os.environ.get("MAILJET_API_SECRET", "")
MAIL_FROM_ADDRESS = os.environ.get("MAIL_FROM_ADDRESS", "")
MAIL_FROM_NAME = os.environ.get("MAIL_FROM_NAME", "FLEXEE · DigitalCo")
# Where invite and registration links point. Defaults to production, not
# localhost: a deployment that forgets this variable would otherwise email every
# student a link to their own machine, and the failure is silent — the mail
# sends, the link is simply dead. A dev checkout overrides it in .env, and
# sends to the console by default anyway.
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "https://mis.flexee.org")

# --- API layer (DRF + JWT + CORS) for the Next.js frontend ---
from datetime import timedelta

INSTALLED_APPS += ['rest_framework', 'corsheaders', 'api']
MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# The Next.js dev server calls this API cross-origin; JWT goes in the
# Authorization header, so no cookies are shared. Set CORS_ALLOWED_ORIGINS for prod.
CORS_ALLOWED_ORIGINS = [
    o for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000,https://digital-co-ui.vercel.app,https://mis.flexee.org'
    ).split(',') if o
]
